class throw {
	Static void divide() throw Arithmetic exception  {
		int s = 22, y = 0, z;
		z = x / y;
	}
	
	public static void main (Strigargs[]) {
		try {
			divide();
		} catch (ArithmeticException e) {
			System.out.println("Caught the eception  " + e;
		} finally {
		System.out.println("I'm always here!");
		}
	}
}
